# PyTorch Tensors Intro
* WELCOME TO PYTORCH TUTORIALS: https://pytorch.org/tutorials/index.html
* PYTORCH EXAMPLES: https://pytorch.org/examples/?utm_source=examples&utm_medium=examples-landing
* PYTORCH CHEAT SHEET: https://pytorch.org/tutorials/beginner/ptcheat.html
* BUILDING MODELS WITH PYTORCH: https://pytorch.org/tutorials/beginner/introyt/modelsyt_tutorial.html?highlight=autograd
* Pytorch Github Tutorials: https://github.com/pytorch/tutorials

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

# Tensors
### In Deep Learning, tensor is the default data structure
* Similar to NumPy NDarrays (N dimentional array)
* Single value tensor is called **scalar**
* 1-dimensional tensor is called a **vector**
* 2-dimensional tensor is often referred to as a **matrix**
* Anything with more than two dimensions is generally just called a **tensor**
* **In PyTorch, every data is some form of a tensor (with different dimensions and shapes)**

In [2]:
# Single value
scalar_tensor = torch.tensor(55)
scalar_tensor

tensor(55)

In [3]:
# List of values
vector_tensor = torch.tensor([22, -3, 55])
vector_tensor

tensor([22, -3, 55])

In [4]:
# 3x3 matrix
matrix_tensor = torch.tensor([
    [22, -3, 55],
    [-2,  5, 11],
    [10, 47, 99]
])
matrix_tensor

tensor([[22, -3, 55],
        [-2,  5, 11],
        [10, 47, 99]])

### Shape (dimensions) of a tensor

In [5]:
scalar_tensor.shape

torch.Size([])

In [6]:
vector_tensor.shape

torch.Size([3])

In [7]:
matrix_tensor.shape

torch.Size([3, 3])

In [8]:
# Or you can call size() method of tensors
matrix_tensor.size()

torch.Size([3, 3])

### Data type (dtype) of a tensor

In [9]:
scalar_tensor.dtype

torch.int64

In [10]:
vector_tensor.dtype

torch.int64

In [11]:
matrix_tensor.dtype

torch.int64

### Note: Most of the time, we need float tensors
#### Neural networks work with floating point numbers

In [12]:
# Pass the dtype when initializing
float_tensor = torch.tensor([22, -3, 55], dtype=torch.float32)
float_tensor

tensor([22., -3., 55.])

In [13]:
# Or you can just use FloatTensor
float_tensor2 = torch.FloatTensor([22, -3, 55])
float_tensor2

tensor([22., -3., 55.])

In [14]:
# Initialize tensor with floating numbers
float_tensor3 = torch.tensor([22.0, -3.0, 55.0])
float_tensor3

tensor([22., -3., 55.])

### Random Tensors

In [15]:
# Normally distributed random numbers
# remember size is the same as shape
random_tensor = torch.randn(size=(2, 3))
random_tensor

tensor([[-0.5573, -0.2986, -0.5553],
        [-0.9897, -0.8661, -0.3819]])

In [16]:
# Call again to get different numbers
random_tensor = torch.randn(size=(2, 3))
random_tensor

tensor([[-1.0513,  0.8982, -0.2578],
        [ 0.4312,  0.4443,  0.3232]])

In [17]:
random_tensor.mean(), random_tensor.std()

(tensor(0.1313), tensor(0.6874))

### Tensor Operations

In [18]:
tensor1 = torch.tensor([22.0, 44.0])
tensor2 = torch.tensor([1.0,  2.0])

### Element-wise operations

In [19]:
print(tensor1 + tensor2)
print(tensor1 - tensor2)
print(tensor1 * tensor2)
print(tensor1 / tensor2)

tensor([23., 46.])
tensor([21., 42.])
tensor([22., 88.])
tensor([22., 22.])


### Broadcasting
* Scalar values are **braodcasted** to all elements
* https://pytorch.org/docs/stable/notes/broadcasting.html

In [20]:
# tensor2 = torch.tensor([1.0,  2.0])
tensor2 + 5

tensor([6., 7.])

In [21]:
tensor2 * 5

tensor([ 5., 10.])

### Advanced Broadcasting Operations
* Start from last dim
* Dims must be equal, 1 or doesn't exist!
* If equal, leave it
* If 1, copy
* If doesn't exist, add dummy dim of 1 (and copy if required)

In [22]:
t1 = torch.randn(2, 3, 25)
t2 = torch.randn(1, 25)

# 25 matched!
# 3 -> 1, copy three times
# 2 don't have matching dim -> add dummy dim of 1 (1, 3, 25)
# 2 -> 1, copy 2 times -> (2, 3, 25)

print(f'{t1.shape=}, {t2.shape=}')

t1.shape=torch.Size([2, 3, 25]), t2.shape=torch.Size([1, 25])


In [23]:
res = t1 + t2
res.shape

torch.Size([2, 3, 25])

In [24]:
t3 = torch.randn(1, 3, 1)
t4 = torch.randn(3)

# t3 -> copy 3 three times (1, 3, 3)
# t4 -> add dummy dim of 1 (1, 3), copy 3 times  (3, 3)
# t4 -> add dummy dim of 1 -> t3: (1, 3, 3) , t4:(1, 3, 3)

print(f'{t3.shape=}, {t4.shape=}')

t3.shape=torch.Size([1, 3, 1]), t4.shape=torch.Size([3])


In [25]:
res = t3 + t4
res.shape

torch.Size([1, 3, 3])

### This operation won't work
* dim of "2" and "3" don't match and can't be broadcasted
* Only dim of "1" can be copied

### Example: Batched RGB Image Data

In [26]:
# Training
# 224x224 RGB image, 32 batch
t7 = torch.randn(32, 3, 224, 224)
t7.shape

torch.Size([32, 3, 224, 224])

In [27]:
# Training is over, prediction over a single image
img_t = torch.randn(3, 224, 224)
img_t.shape

torch.Size([3, 224, 224])

### Adding Dimensions

In [28]:
imt_t_with_batch = img_t.unsqueeze(0)

In [29]:
imt_t_with_batch.shape

torch.Size([1, 3, 224, 224])

#### Add dim with extra row
* NOTE: this is different than adding "1" as dimension
* In this case, we actually add useful information

In [30]:
# 4x3 matrix
t9 = torch.tensor([
    [22, -3, 55],
    [-2,  5, 11],
    [10, 47, 99],
    [10, 47, 99]
])
t9

tensor([[22, -3, 55],
        [-2,  5, 11],
        [10, 47, 99],
        [10, 47, 99]])

In [31]:
t9.shape

torch.Size([4, 3])

### Adding dimension of "1" will not add useful information
* Usually dim of "1" regarded as "dummy dimension"

In [32]:
t9_2 = t9.unsqueeze(0).unsqueeze(0).unsqueeze(0).unsqueeze(0)

In [33]:
t9_2

tensor([[[[[[22, -3, 55],
            [-2,  5, 11],
            [10, 47, 99],
            [10, 47, 99]]]]]])

### Vector and Matrix Operations

In [34]:
tensor1

tensor([22., 44.])

In [35]:
tensor2

tensor([1., 2.])

In [36]:
22.0*1.0 + 44.0*2.0

110.0

In [37]:
# Dot product
# (22.0*1.0) + (44.0*2.0)
torch.dot(tensor1, tensor2)

tensor(110.)

In [38]:
# Matrix multiplication
# (2x2) * (2x2) -> result will be a 2x2 matrix
matrix_tensor1 = torch.tensor([
    [22, -3],
    [-2,  5],
])

matrix_tensor2 = torch.tensor([
    [10, 3],
    [1,  5],
])

torch.mm(matrix_tensor1, matrix_tensor2)

tensor([[217,  51],
        [-15,  19]])

### Non-Destructive Operations
* By default, a new tensor is created on function calls

In [39]:
tensor4 = torch.tensor([2.0, 3.0])
tensor4.pow(2)

tensor([4., 9.])

In [40]:
tensor4

tensor([2., 3.])

### In-place operation
* Notice we use **pow_()** not pow()
* Underline at the end has special meaning in PyTorch
* It represents in-place (overwriting) operation 

In [41]:
tensor4.pow_(2)
tensor4

tensor([4., 9.])

### Copying Tensors
* Assigning a tensor to a variable makes the variable a referance of the tensor, and does not copy it (**"pass by referance"**)

In [42]:
tensor5 = torch.tensor([55.0, 66.0])
tensor6 = tensor5
tensor6

tensor([55., 66.])

In [43]:
tensor5.pow_(2)

# Both are modified, tensor6 refers to tensor5 by memory
print(tensor5)
print(tensor6)

tensor([3025., 4356.])
tensor([3025., 4356.])


### Use *clone()* instead

In [44]:
tensor5 = torch.tensor([55.0, 66.0])
tensor5_copy = tensor5.clone()

In [45]:
tensor5.pow_(2)

# Clone is not modified, it is a different tensor
print(tensor5)
print(tensor5_copy)

tensor([3025., 4356.])
tensor([55., 66.])


### From Numpy array

In [46]:
import numpy as np

np_array = np.array([47.0, -3.0, 99.0, 105.0])
np_array

array([ 47.,  -3.,  99., 105.])

In [47]:
# You can just pass in, NumPy arrays are supported by default
tensor_from_np = torch.tensor(np_array)
tensor_from_np

tensor([ 47.,  -3.,  99., 105.], dtype=torch.float64)

### Covert Tensor to NumPy Array

In [48]:
tensor7 = torch.tensor([-5.0, 2.0])
tensor7

tensor([-5.,  2.])

In [49]:
tensor7.numpy()

array([-5.,  2.], dtype=float32)

### Covert Tensor to Basic Python 

In [50]:
tensor7.tolist()

[-5.0, 2.0]

### Covert Scalar Tensor to a single Python number
* NOTE: item() function only works on scalars!

In [51]:
tensor8 = torch.tensor(100.0)
tensor8.item()

100.0

In [52]:
print(type(tensor8))
print(type(tensor8.item()))

<class 'torch.Tensor'>
<class 'float'>


# Moving tensors to GPU and back

In [53]:
if torch.cuda.is_available():
    print('GPU is available')
else:
    print('GPU is not available, CPU only')

GPU is available


In [54]:
# Initialize tensor directly on GPU
# cuda:0 means that first GPU
# In Deep learning, it is common to use multiple GPUs
tensor_cuda = torch.tensor([-5.0, 2.0], device='cuda:0')
tensor_cuda

tensor([-5.,  2.], device='cuda:0')

In [55]:
# Move CPU initialized tensor to GPU
tensor_cpu = torch.tensor([-5.0, 2.0])
tensor_cuda = tensor_cpu.to('cuda:0')
tensor_cuda

tensor([-5.,  2.], device='cuda:0')

### Move GPU tensor back to CPU

In [56]:
tensor_cpu_back = tensor_cuda.to('cpu')
tensor_cpu_back

tensor([-5.,  2.])

### Alternatively you can use *cpu()* and *cuda()*

In [57]:
tensor_cpu = torch.tensor([-5.0, 2.0])
tensor_cuda = tensor_cpu.cuda()
tensor_cuda

tensor([-5.,  2.], device='cuda:0')

In [58]:
tensor_cpu_back = tensor_cuda.cpu()
tensor_cpu_back

tensor([-5.,  2.])